// vue/calculator/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display :value = "displayValue"></Display>
        <Button label="AC" triple @onCalcButtonClick="clearMemory"></Button>
        <Button label="/" operation @onCalcButtonClick="setOperation"></Button>
        <Button label="7" @onCalcButtonClick="addDigit"></Button>
        <Button label="8" @onCalcButtonClick="addDigit"></Button>
        <Button label="9" @onCalcButtonClick="addDigit"></Button>
        <Button label="*" operation @onCalcButtonClick="setOperation"></Button>
        <Button label="4" @onCalcButtonClick="addDigit"></Button>
        <Button label="5" @onCalcButtonClick="addDigit"></Button>
        <Button label="6" @onCalcButtonClick="addDigit"></Button>
        <Button label="-" operation @onCalcButtonClick="setOperation"></Button>
        <Button label="1" @onCalcButtonClick="addDigit"></Button>
        <Button label="2" @onCalcButtonClick="addDigit"></Button>
        <Button label="3" @onCalcButtonClick="addDigit"></Button>
        <Button label="+" operation @onCalcButtonClick="setOperation"></Button>
        <Button label="0" double @onCalcButtonClick="addDigit"></Button>
        <Button label="." @onCalcButtonClick="addDigit"></Button>
        <Button label="=" operation @onCalcButtonClick="setOperation"></Button>
    </div>
</template>

<script>
import Display from "../Components/Display"
import Button from "../Components/Button"

export default {
    data: function(){
        return{
            displayValue: "0",
            clearDisplay: false,
            operation: null,
            values: [0,0],
            current: 0
        }
    },
    components: {Button,Display},
    methods:{
        clearMemory(){
            Object.assign(this.$data, this.$options.data())
        },
        setOperation(operation){
            if(this.current === 0){
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
            } else{
                const equals = operation === '='
                const currentOperation = this.operation

                try {
                    this.values[0] = eval(`${this.values[0]} ${currentOperation} ${this.values[1]}`)
                } catch (error) {
                this.$emit('onError',error)
                }

                this.values[1] = 0
                this.displayValue = this.values[0]
                this.operation = equals? null : operation
                this.clearDisplay = !equals
                this.current = equals? 0:1
            }
        },
        addDigit(n){
            if(n === '.' && this.displayValue.includes(".")){
                return
            }

            const clearDisplay = (this.displayValue === '0') || this.clearDisplay
            const currentValue = clearDisplay? "" : this.displayValue
            const displayValue = currentValue + n

            this.displayValue = displayValue
            this.clearDisplay = false

            if(n!== '.'){
                const i = this.current
                const newValue = parseFloat(displayValue)
                this.values[i] = newValue
            }
        }
    }

}
</script>

<style>

.calculator{
    height: 320px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;

    display: grid;
    grid-template-columns: repeat(4,25%);
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}

</style>

// React/calculadora/src/main/Calculator.jsx
import React, {Component} from 'react'
import './Calculator.css'

import Button from '../components/Button'
import Display from '../components/Display'

const initialState = {
    displayValue : '0',
    clearDisplay : false,
    operation : null,
    values: [0,0],
    current: 0
}

export default class Calculator extends Component{
    state = {...initialState}
    clearMemory(){
        this.setState({...initialState})
    }
    setOperation(operation){
        if(this.state.current === 0){
            this.setState({operation,current:1,clearDisplay:true})
        }else{
            const equals = operation === '='
            const currentOperation = this.state.operation

            const values = [...this.state.values]
            try {
                values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`)
            } catch (error) {
                values[0] = this.state.values[0]
            }
            values[1] = 0

            this.setState({
                displayValue: values[0],
                operation : equals? null: operation,
                current: equals? 0:1,
                clearDisplay: true,
                values : values
            })
        }
    }
    addDigit(n){
        if(n === '.' && this.state.displayValue.includes('.')){
            return
        }

        const clearDisplay = this.state.displayValue === '0' || this.state.clearDisplay
        const currentValue = clearDisplay ? '' : this.state.displayValue
        const displayValue= currentValue + n; //diferente
        this.setState({displayValue,clearDisplay: false})

        if(n !== '.'){
            const i = this.state.current
            const newValue = parseFloat(displayValue)
            const values = [...this.state.values]
            values[i] = newValue
            this.setState({values})
        }
    }
    render(){
        const addDigit = n => this.addDigit(n)
        const setOperation = n => this.setOperation(n)
        return (
            <div className="calculator">
                <Display value = {this.state.displayValue}></Display> 
                <Button label = 'AC' triple click ={() => this.clearMemory()} />
                <Button label = '/' operation click={setOperation}/>
                <Button label = '7' click = {addDigit}/>
                <Button label = '8' click = {addDigit}/>
                <Button label = '9' click = {addDigit}/>
                <Button label = '*' click = {setOperation} operation/>
                <Button label = '4' click = {addDigit}/>
                <Button label = '5' click = {addDigit}/>
                <Button label = '6' click = {addDigit}/>
                <Button label = '-' click = {setOperation} operation/>
                <Button label = '1' click = {addDigit}/>
                <Button label = '2' click = {addDigit}/>
                <Button label = '3' click = {addDigit}/>
                <Button label = '+' click = {setOperation} operation/>
                <Button label = '0' click = {addDigit} double/>
                <Button label = '.' click = {addDigit}/>
                <Button label = '=' click = {setOperation} operation/>
            </div>
        )
    }
}
